theme: jekyll-theme-slate
title: ShoopDaLoop
seo_title: ShoopDaLoop - Limitless Live Looping
description: limitless live looping
logo: /assets/img/logo.png
screenshot: /assets/img/screenshot.png

github:
  repository_url: https://github.com/SanderVocke/shoopdaloop
  owner_name: Sander Vocke