theme: jekyll-theme-slate
title: ShoopDaLoop
description: Limitless live looping
logo: /assets/img/logo.png

github:
  repository_url: https://github.com/SanderVocke/shoopdaloop
  owner_name: Sander Vocke